name: pog4_rf_sweep
method: bayes
metric:
  name: RMSE
  goal: minimize
parameters:
  n_estimators:
    min: 10
    max: 2000
  max_depth:
    min: 5
    max: 100
  min_samples_split:
    min: 2
    max: 10
  min_samples_leaf:
    min: 1
    max: 10
  max_features:
    values: ["auto"]
  scaler:
    values: [minmax, robust]
  imputer:
    values: [mean, median, most_frequent]
early_terminate:
  type: hyperband
  max_iter: 100
  s: 2