name: pog4_svm_sweep
method: bayes
metric:
  name: RMSE
  goal: minimize
parameters:
  C:
    min: 0.1
    max: 100.0
  epsilon:
    min: 0.01
    max: 1.0
  gamma:
    min: 0.001
    max: 1.0
  kernel:
    values: ["linear", "poly", "rbf", "sigmoid"]
  imputer:
    values: ["mean", "median", "most_frequent"]
  scaler:
    values: ["minmax", "standard", "robust"]
